version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=authdb
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # NOTE: 5433 on host, 5432 inside container
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
